nb_main_homepage:
    path:     /
    defaults: { _controller: NBMainBundle:Main:index }
nb_main_liste_des_compagnie:
    path:     /compagnie/liste-des-compagnie
    defaults: { _controller: NBMainBundle:Compagnie:list }
nb_main_ajouter_compagnie:
    path:     /compagnie/ajouter-une-compagnie
    defaults: { _controller: NBMainBundle:Compagnie:add }
nb_main_modifier_compagnie:
    path:     /compagnie/modifier-une-compagnie/{id}
    defaults: { _controller: NBMainBundle:Compagnie:edit }
nb_main_supprimer_compagnie:
    path:     /compagnie/supprimer-une-compagnie/{id}
    defaults: { _controller: NBMainBundle:Compagnie:delete }
nb_main_liste_utilisateur_compagnie:
    path:     /compagnie/liste-utilisateur-compagnie/{compagnie_id}
    defaults: { _controller: NBMainBundle:Compagnie:users }
nb_main_ajouter_compagnie_utilisateur:
    path:     /compagnie/liste-utilisateur-compagnie/{compagnie_id}/nouveau
    defaults: { _controller: NBMainBundle:Compagnie:usersAdd }
nb_main_liste_seatseller:
    path:     /seatseller/liste-seatseller
    defaults: { _controller: NBMainBundle:seatseller:list }
nb_main_modifier_seatseller:
    path:     /seatseller/modifier-seatseller
    defaults: { _controller: NBMainBundle:seatseller:edit }
nb_main_liste_des_axes:
    path:     /axes/liste-des-axes
    defaults: { _controller: NBMainBundle:Axes:list }
nb_main_ajouter_axes:
    path:     /axes/ajouter-des-axes
    defaults: { _controller: NBMainBundle:Axes:add }
nb_main_modifier_axes:
    path:     /axes/modifier-un-axe/{id}
    defaults: { _controller: NBMainBundle:Axes:edit }
nb_main_liste_des_villes:
    path:     /villes/liste-des-villes
    defaults: { _controller: NBMainBundle:Villes:list }
nb_main_ajouter_des_villes:
    path:     /viles/ajouter-une-ville
    defaults: { _controller: NBMainBundle:Villes:add }
nb_main_modifier_villes:
    path:     /villes/modifier-une-ville/{id}
    defaults: { _controller: NBMainBundle:Villes:edit }
nb_main_liste_des_voyages:
    path:     /voyages/liste-des-voyages
    defaults: { _controller: NBMainBundle:Voyages:list }
nb_main_ajouter_des_voyages:
    path:     /voyages/ajouter-des-voyages
    defaults: { _controller: NBMainBundle:Voyages:add }
nb_main_modifier_voyages:
    path:     /voyages/modifier-un-voyage/{id}
    defaults: { _controller: NBMainBundle:Voyages:edit }

nb_main_liste_des_point_embarquement:
    path:     /voyages/point-embarquement
    defaults: { _controller: NBMainBundle:Point:list }
nb_main_ajouter_des_point_embarquement:
    path:     /voyages/point-embarquement/nouveau
    defaults: { _controller: NBMainBundle:Point:add }
nb_main_modifier_des_point_embarquement:
    path:     /voyages/modifier-point-embarquement/{id}
    defaults: { _controller: NBMainBundle:Point:edit }

nb_main_liste_gestion_des_promotions:
    path:     /promotions/liste-gestion-des-promotions
    defaults: { _controller: NBMainBundle:Promotions:list }
nb_main_modifier_gestion_des_promotions:
    path:     /promotions/modifier-une-promotion/{id}
    defaults: { _controller: NBMainBundle:Promotions:edit }
nb_main_termes_et_conditions:
    path:     /cms/termes-et-conditions
    defaults: { _controller: NBMainBundle:CMS:TermesConditions }
nb_main_confidentialite:
    path:     /cms/confidentialites
    defaults: { _controller: NBMainBundle:CMS:Confidentialite }
nb_main_blog:
    path:     /cms/blog
    defaults: { _controller: NBMainBundle:CMS:Blog }
nb_main_professionel:
    path:     /cms/professionel
    defaults: { _controller: NBMainBundle:CMS:Professionel }
nb_main_modification_voyage:
    path:     /cms/modification-voyage
    defaults: { _controller: NBMainBundle:CMS:ModificationVoyage }
nb_main_annulation_voyage:
    path:     /cms/annulation-voyage
    defaults: { _controller: NBMainBundle:CMS:AnnulationVoyage }
nb_main_liste_gestion_newsletter:
    path:     /gest_newsletter/liste-gestion-newsletter
    defaults: { _controller: NBMainBundle:GestionNewsletter:list }
nb_main_modifier_gestion_newsletter:
    path:     /gest_newsletter/modifier-gestion-newsletter
    defaults: { _controller: NBMainBundle:GestionNewsletter:edit }





